[2025-02-12T19:19:00.225+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T19:19:00.237+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superstore_dag.run_dbt_fact_orders scheduled__2025-02-11T00:00:00+00:00 [queued]>
[2025-02-12T19:19:00.243+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superstore_dag.run_dbt_fact_orders scheduled__2025-02-11T00:00:00+00:00 [queued]>
[2025-02-12T19:19:00.251+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-12T19:19:00.262+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_dbt_fact_orders> on 2025-02-11 00:00:00+00:00
[2025-02-12T19:19:00.266+0000] {standard_task_runner.py:72} INFO - Started process 221 to run task
[2025-02-12T19:19:00.268+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'superstore_dag', 'run_dbt_fact_orders', 'scheduled__2025-02-11T00:00:00+00:00', '--job-id', '216', '--raw', '--subdir', 'DAGS_FOLDER/superstore_dag.py', '--cfg-path', '/tmp/tmpihngp6xn']
[2025-02-12T19:19:00.271+0000] {standard_task_runner.py:105} INFO - Job 216: Subtask run_dbt_fact_orders
[2025-02-12T19:19:00.288+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-12T19:19:00.317+0000] {task_command.py:467} INFO - Running <TaskInstance: superstore_dag.run_dbt_fact_orders scheduled__2025-02-11T00:00:00+00:00 [running]> on host 9cd0ccfaeb2e
[2025-02-12T19:19:00.319+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-12T19:19:00.390+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='superstore_dag' AIRFLOW_CTX_TASK_ID='run_dbt_fact_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-11T00:00:00+00:00'
[2025-02-12T19:19:00.391+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-12T19:19:00.404+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-12T19:19:00.406+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /dbt/superstore/ && dbt run --select fact_orders']
[2025-02-12T19:19:00.412+0000] {subprocess.py:99} INFO - Output:
[2025-02-12T19:19:02.108+0000] {subprocess.py:106} INFO - [0m19:19:02  Running with dbt=1.9.2
[2025-02-12T19:19:02.339+0000] {subprocess.py:106} INFO - [0m19:19:02  Registered adapter: postgres=1.9.0
[2025-02-12T19:19:02.782+0000] {subprocess.py:106} INFO - [0m19:19:02  Found 5 models, 10 data tests, 1 source, 431 macros
[2025-02-12T19:19:02.785+0000] {subprocess.py:106} INFO - [0m19:19:02
[2025-02-12T19:19:02.785+0000] {subprocess.py:106} INFO - [0m19:19:02  Concurrency: 1 threads (target='prod')
[2025-02-12T19:19:02.786+0000] {subprocess.py:106} INFO - [0m19:19:02
[2025-02-12T19:19:02.868+0000] {subprocess.py:106} INFO - [0m19:19:02  1 of 1 START sql incremental model core.fact_orders ............................ [RUN]
[2025-02-12T19:19:03.064+0000] {subprocess.py:106} INFO - [0m19:19:03  1 of 1 OK created sql incremental model core.fact_orders ....................... [[32mINSERT 0 0[0m in 0.19s]
[2025-02-12T19:19:03.079+0000] {subprocess.py:106} INFO - [0m19:19:03
[2025-02-12T19:19:03.079+0000] {subprocess.py:106} INFO - [0m19:19:03  Finished running 1 incremental model in 0 hours 0 minutes and 0.29 seconds (0.29s).
[2025-02-12T19:19:03.129+0000] {subprocess.py:106} INFO - [0m19:19:03
[2025-02-12T19:19:03.129+0000] {subprocess.py:106} INFO - [0m19:19:03  [32mCompleted successfully[0m
[2025-02-12T19:19:03.130+0000] {subprocess.py:106} INFO - [0m19:19:03
[2025-02-12T19:19:03.130+0000] {subprocess.py:106} INFO - [0m19:19:03  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-12T19:19:04.046+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-12T19:19:04.064+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-12T19:19:04.064+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=superstore_dag, task_id=run_dbt_fact_orders, run_id=scheduled__2025-02-11T00:00:00+00:00, execution_date=20250211T000000, start_date=20250212T191900, end_date=20250212T191904
[2025-02-12T19:19:04.090+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-12T19:19:04.101+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-12T19:19:04.103+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
