[2025-02-05T17:12:21.585+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-05T17:12:21.602+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.load_data scheduled__2025-02-04T00:00:00+00:00 [queued]>
[2025-02-05T17:12:21.612+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.load_data scheduled__2025-02-04T00:00:00+00:00 [queued]>
[2025-02-05T17:12:21.613+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-05T17:12:21.627+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data> on 2025-02-04 00:00:00+00:00
[2025-02-05T17:12:21.632+0000] {standard_task_runner.py:72} INFO - Started process 95 to run task
[2025-02-05T17:12:21.641+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'load_data', 'scheduled__2025-02-04T00:00:00+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp1dxz5e1f']
[2025-02-05T17:12:21.646+0000] {standard_task_runner.py:105} INFO - Job 161: Subtask load_data
[2025-02-05T17:12:21.690+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-05T17:12:21.918+0000] {task_command.py:467} INFO - Running <TaskInstance: first_dag.load_data scheduled__2025-02-04T00:00:00+00:00 [running]> on host 3dd8da0a9dae
[2025-02-05T17:12:21.922+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-05T17:12:22.171+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-04T00:00:00+00:00'
[2025-02-05T17:12:22.174+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-05T17:12:22.892+0000] {base.py:84} INFO - Retrieving connection 'my_dwh_conn'
[2025-02-05T17:12:24.057+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-05T17:12:24.068+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-05T17:12:24.073+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=load_data, run_id=scheduled__2025-02-04T00:00:00+00:00, execution_date=20250204T000000, start_date=20250205T171221, end_date=20250205T171224
[2025-02-05T17:12:24.101+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-05T17:12:24.117+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T17:12:24.119+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
