[2025-01-18T09:46:02.298+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-18T09:46:02.314+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.load_data manual__2025-01-18T09:45:55.560493+00:00 [queued]>
[2025-01-18T09:46:02.325+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.load_data manual__2025-01-18T09:45:55.560493+00:00 [queued]>
[2025-01-18T09:46:02.326+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-18T09:46:02.338+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data> on 2025-01-18 09:45:55.560493+00:00
[2025-01-18T09:46:02.343+0000] {standard_task_runner.py:72} INFO - Started process 680 to run task
[2025-01-18T09:46:02.346+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'load_data', 'manual__2025-01-18T09:45:55.560493+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpb8zlbmek']
[2025-01-18T09:46:02.348+0000] {standard_task_runner.py:105} INFO - Job 51: Subtask load_data
[2025-01-18T09:46:02.363+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-18T09:46:02.399+0000] {task_command.py:467} INFO - Running <TaskInstance: first_dag.load_data manual__2025-01-18T09:45:55.560493+00:00 [running]> on host 9fe2ea257df4
[2025-01-18T09:46:02.473+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-18T09:45:55.560493+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-18T09:45:55.560493+00:00'
[2025-01-18T09:46:02.474+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-18T09:46:02.813+0000] {base.py:84} INFO - Retrieving connection 'my_dwh_conn'
[2025-01-18T09:46:03.577+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-18T09:46:03.586+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-18T09:46:03.587+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=load_data, run_id=manual__2025-01-18T09:45:55.560493+00:00, execution_date=20250118T094555, start_date=20250118T094602, end_date=20250118T094603
[2025-01-18T09:46:03.645+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-18T09:46:03.674+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-18T09:46:03.677+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
