[2025-01-20T16:29:12.728+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-20T16:29:12.740+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.load_data scheduled__2025-01-19T00:00:00+00:00 [queued]>
[2025-01-20T16:29:12.747+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.load_data scheduled__2025-01-19T00:00:00+00:00 [queued]>
[2025-01-20T16:29:12.749+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-20T16:29:12.759+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data> on 2025-01-19 00:00:00+00:00
[2025-01-20T16:29:12.763+0000] {standard_task_runner.py:72} INFO - Started process 135 to run task
[2025-01-20T16:29:12.765+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'load_data', 'scheduled__2025-01-19T00:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp0dyn39zj']
[2025-01-20T16:29:12.767+0000] {standard_task_runner.py:105} INFO - Job 64: Subtask load_data
[2025-01-20T16:29:12.788+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-20T16:29:12.825+0000] {task_command.py:467} INFO - Running <TaskInstance: first_dag.load_data scheduled__2025-01-19T00:00:00+00:00 [running]> on host 9fe2ea257df4
[2025-01-20T16:29:12.826+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-20T16:29:12.899+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-19T00:00:00+00:00'
[2025-01-20T16:29:12.900+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-20T16:29:13.276+0000] {base.py:84} INFO - Retrieving connection 'my_dwh_conn'
[2025-01-20T16:29:13.994+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-20T16:29:14.002+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-20T16:29:14.003+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=load_data, run_id=scheduled__2025-01-19T00:00:00+00:00, execution_date=20250119T000000, start_date=20250120T162912, end_date=20250120T162914
[2025-01-20T16:29:14.024+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-20T16:29:14.037+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-20T16:29:14.040+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
