[2025-01-28T18:02:43.619+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-28T18:02:43.630+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.load_data scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-01-28T18:02:43.635+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.load_data scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-01-28T18:02:43.642+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-28T18:02:43.651+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data> on 2025-01-27 00:00:00+00:00
[2025-01-28T18:02:43.654+0000] {standard_task_runner.py:72} INFO - Started process 95 to run task
[2025-01-28T18:02:43.656+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'load_data', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpdb0l0w35']
[2025-01-28T18:02:43.657+0000] {standard_task_runner.py:105} INFO - Job 89: Subtask load_data
[2025-01-28T18:02:43.671+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-28T18:02:43.699+0000] {task_command.py:467} INFO - Running <TaskInstance: first_dag.load_data scheduled__2025-01-27T00:00:00+00:00 [running]> on host 4a00e32dbae7
[2025-01-28T18:02:43.700+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-28T18:02:43.779+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-01-28T18:02:43.780+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-28T18:02:44.076+0000] {base.py:84} INFO - Retrieving connection 'my_dwh_conn'
[2025-01-28T18:02:44.770+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-28T18:02:44.782+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-28T18:02:44.782+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=load_data, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250128T180243, end_date=20250128T180244
[2025-01-28T18:02:44.833+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-28T18:02:44.846+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-28T18:02:44.854+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
