[2025-02-08T18:07:10.169+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T18:07:10.180+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dim_location.run_dbt_dim_date manual__2025-02-08T18:06:52.546597+00:00 [queued]>
[2025-02-08T18:07:10.185+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dim_location.run_dbt_dim_date manual__2025-02-08T18:06:52.546597+00:00 [queued]>
[2025-02-08T18:07:10.186+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-08T18:07:10.195+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_dbt_dim_date> on 2025-02-08 18:06:52.546597+00:00
[2025-02-08T18:07:10.200+0000] {standard_task_runner.py:72} INFO - Started process 890 to run task
[2025-02-08T18:07:10.201+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dim_location', 'run_dbt_dim_date', 'manual__2025-02-08T18:06:52.546597+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/dim_location.py', '--cfg-path', '/tmp/tmpavnij11x']
[2025-02-08T18:07:10.203+0000] {standard_task_runner.py:105} INFO - Job 192: Subtask run_dbt_dim_date
[2025-02-08T18:07:10.214+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-08T18:07:10.238+0000] {task_command.py:467} INFO - Running <TaskInstance: dim_location.run_dbt_dim_date manual__2025-02-08T18:06:52.546597+00:00 [running]> on host 9cd0ccfaeb2e
[2025-02-08T18:07:10.292+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dim_location' AIRFLOW_CTX_TASK_ID='run_dbt_dim_date' AIRFLOW_CTX_EXECUTION_DATE='2025-02-08T18:06:52.546597+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-08T18:06:52.546597+00:00'
[2025-02-08T18:07:10.293+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T18:07:10.304+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-08T18:07:10.305+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /dbt/superstore/ && dbt run --select dim_date']
[2025-02-08T18:07:10.313+0000] {subprocess.py:99} INFO - Output:
[2025-02-08T18:07:11.836+0000] {subprocess.py:106} INFO - [0m18:07:11  Running with dbt=1.9.2
[2025-02-08T18:07:12.058+0000] {subprocess.py:106} INFO - [0m18:07:12  Registered adapter: postgres=1.9.0
[2025-02-08T18:07:12.349+0000] {subprocess.py:106} INFO - [0m18:07:12  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-02-08T18:07:12.349+0000] {subprocess.py:106} INFO - There are 1 unused configuration paths:
[2025-02-08T18:07:12.350+0000] {subprocess.py:106} INFO - - models.superstore_project.dim_customer
[2025-02-08T18:07:12.498+0000] {subprocess.py:106} INFO - [0m18:07:12  Found 5 models, 8 data tests, 1 source, 431 macros
[2025-02-08T18:07:12.500+0000] {subprocess.py:106} INFO - [0m18:07:12
[2025-02-08T18:07:12.501+0000] {subprocess.py:106} INFO - [0m18:07:12  Concurrency: 1 threads (target='prod')
[2025-02-08T18:07:12.501+0000] {subprocess.py:106} INFO - [0m18:07:12
[2025-02-08T18:07:12.574+0000] {subprocess.py:106} INFO - [0m18:07:12  1 of 1 START sql incremental model core.dim_date ............................... [RUN]
[2025-02-08T18:07:12.718+0000] {subprocess.py:106} INFO - [0m18:07:12  1 of 1 OK created sql incremental model core.dim_date .......................... [[32mINSERT 0 0[0m in 0.14s]
[2025-02-08T18:07:12.728+0000] {subprocess.py:106} INFO - [0m18:07:12
[2025-02-08T18:07:12.729+0000] {subprocess.py:106} INFO - [0m18:07:12  Finished running 1 incremental model in 0 hours 0 minutes and 0.23 seconds (0.23s).
[2025-02-08T18:07:12.768+0000] {subprocess.py:106} INFO - [0m18:07:12
[2025-02-08T18:07:12.768+0000] {subprocess.py:106} INFO - [0m18:07:12  [32mCompleted successfully[0m
[2025-02-08T18:07:12.768+0000] {subprocess.py:106} INFO - [0m18:07:12
[2025-02-08T18:07:12.769+0000] {subprocess.py:106} INFO - [0m18:07:12  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-08T18:07:13.581+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-08T18:07:13.600+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T18:07:13.601+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dim_location, task_id=run_dbt_dim_date, run_id=manual__2025-02-08T18:06:52.546597+00:00, execution_date=20250208T180652, start_date=20250208T180710, end_date=20250208T180713
[2025-02-08T18:07:13.622+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T18:07:13.636+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T18:07:13.638+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
