[2025-02-12T19:18:29.102+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T19:18:29.115+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superstore_dag.run_dbt_dim_product scheduled__2025-02-11T00:00:00+00:00 [queued]>
[2025-02-12T19:18:29.121+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superstore_dag.run_dbt_dim_product scheduled__2025-02-11T00:00:00+00:00 [queued]>
[2025-02-12T19:18:29.121+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-12T19:18:29.132+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_dbt_dim_product> on 2025-02-11 00:00:00+00:00
[2025-02-12T19:18:29.135+0000] {standard_task_runner.py:72} INFO - Started process 75 to run task
[2025-02-12T19:18:29.137+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'superstore_dag', 'run_dbt_dim_product', 'scheduled__2025-02-11T00:00:00+00:00', '--job-id', '212', '--raw', '--subdir', 'DAGS_FOLDER/superstore_dag.py', '--cfg-path', '/tmp/tmpcv60i1ve']
[2025-02-12T19:18:29.139+0000] {standard_task_runner.py:105} INFO - Job 212: Subtask run_dbt_dim_product
[2025-02-12T19:18:29.153+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-12T19:18:29.185+0000] {task_command.py:467} INFO - Running <TaskInstance: superstore_dag.run_dbt_dim_product scheduled__2025-02-11T00:00:00+00:00 [running]> on host 9cd0ccfaeb2e
[2025-02-12T19:18:29.186+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-12T19:18:29.255+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='superstore_dag' AIRFLOW_CTX_TASK_ID='run_dbt_dim_product' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-11T00:00:00+00:00'
[2025-02-12T19:18:29.257+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-12T19:18:29.275+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-12T19:18:29.276+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /dbt/superstore/ && dbt run --select dim_product']
[2025-02-12T19:18:29.282+0000] {subprocess.py:99} INFO - Output:
[2025-02-12T19:18:31.428+0000] {subprocess.py:106} INFO - [0m19:18:31  Running with dbt=1.9.2
[2025-02-12T19:18:31.732+0000] {subprocess.py:106} INFO - [0m19:18:31  Registered adapter: postgres=1.9.0
[2025-02-12T19:18:31.901+0000] {subprocess.py:106} INFO - [0m19:18:31  Unable to do partial parsing because profile has changed
[2025-02-12T19:18:33.055+0000] {subprocess.py:106} INFO - [0m19:18:33  [[33mWARNING[0m]: Did not find matching node for patch with name 'fact_sales' in the 'models' section of file 'models/example/schema.yml'
[2025-02-12T19:18:33.392+0000] {subprocess.py:106} INFO - [0m19:18:33  [[33mWARNING[0m]: Test 'test.superstore_project.unique_fact_sales_order_hash_key.955b6af71f' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:33.404+0000] {subprocess.py:106} INFO - [0m19:18:33  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_order_hash_key.ef4146245b' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:33.410+0000] {subprocess.py:106} INFO - [0m19:18:33  [[33mWARNING[0m]: Test 'test.superstore_project.unique_fact_sales_order_id.27d0b5b8b9' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:33.411+0000] {subprocess.py:106} INFO - [0m19:18:33  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_order_id.f6f073d70b' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:33.420+0000] {subprocess.py:106} INFO - [0m19:18:33  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_customer_hash_key.1fc8c11439' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:33.430+0000] {subprocess.py:106} INFO - [0m19:18:33  [[33mWARNING[0m]: Test 'test.superstore_project.relationships_fact_sales_customer_hash_key__customer_hash_key__ref_dim_customer_.17da0cebd2' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:33.446+0000] {subprocess.py:106} INFO - [0m19:18:33  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_product_hash_key.a3a002cd4b' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:33.451+0000] {subprocess.py:106} INFO - [0m19:18:33  [[33mWARNING[0m]: Test 'test.superstore_project.relationships_fact_sales_product_hash_key__product_hash_key__ref_dim_product_.c5bbd01abb' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:33.452+0000] {subprocess.py:106} INFO - [0m19:18:33  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_location_hash_key.2ae8fd54cc' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:33.453+0000] {subprocess.py:106} INFO - [0m19:18:33  [[33mWARNING[0m]: Test 'test.superstore_project.relationships_fact_sales_location_hash_key__location_hash_key__ref_dim_location_.dc1a855dfb' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:33.455+0000] {subprocess.py:106} INFO - [0m19:18:33  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_order_date.d04f309174' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:33.456+0000] {subprocess.py:106} INFO - [0m19:18:33  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_ship_date.2574bac0f3' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:33.457+0000] {subprocess.py:106} INFO - [0m19:18:33  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_sales.2251c04d7d' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:33.457+0000] {subprocess.py:106} INFO - [0m19:18:33  [[33mWARNING[0m]: Test 'test.superstore_project.dbt_utils_expression_is_true_fact_sales_sales__sales_0.7f4fbe8968' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:33.458+0000] {subprocess.py:106} INFO - [0m19:18:33  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_quantity.123217c37f' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:33.458+0000] {subprocess.py:106} INFO - [0m19:18:33  [[33mWARNING[0m]: Test 'test.superstore_project.dbt_utils_expression_is_true_fact_sales_quantity__quantity_0.7112c44c4b' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:33.459+0000] {subprocess.py:106} INFO - [0m19:18:33  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_discount.22010f5285' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:33.460+0000] {subprocess.py:106} INFO - [0m19:18:33  [[33mWARNING[0m]: Test 'test.superstore_project.dbt_utils_expression_is_true_fact_sales_discount__discount_0.37582520d5' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:33.466+0000] {subprocess.py:106} INFO - [0m19:18:33  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_profit.c7a9f000f9' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:33.542+0000] {subprocess.py:106} INFO - [0m19:18:33  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-02-12T19:18:33.542+0000] {subprocess.py:106} INFO - There are 1 unused configuration paths:
[2025-02-12T19:18:33.547+0000] {subprocess.py:106} INFO - - models.superstore_project.dim_product
[2025-02-12T19:18:33.765+0000] {subprocess.py:106} INFO - [0m19:18:33  Found 5 models, 10 data tests, 1 source, 431 macros
[2025-02-12T19:18:33.768+0000] {subprocess.py:106} INFO - [0m19:18:33
[2025-02-12T19:18:33.769+0000] {subprocess.py:106} INFO - [0m19:18:33  Concurrency: 1 threads (target='prod')
[2025-02-12T19:18:33.770+0000] {subprocess.py:106} INFO - [0m19:18:33
[2025-02-12T19:18:33.914+0000] {subprocess.py:106} INFO - [0m19:18:33  1 of 1 START sql incremental model core.dim_product ............................ [RUN]
[2025-02-12T19:18:34.169+0000] {subprocess.py:106} INFO - [0m19:18:34  1 of 1 OK created sql incremental model core.dim_product ....................... [[32mINSERT 0 8474[0m in 0.25s]
[2025-02-12T19:18:34.184+0000] {subprocess.py:106} INFO - [0m19:18:34
[2025-02-12T19:18:34.184+0000] {subprocess.py:106} INFO - [0m19:18:34  Finished running 1 incremental model in 0 hours 0 minutes and 0.41 seconds (0.41s).
[2025-02-12T19:18:34.259+0000] {subprocess.py:106} INFO - [0m19:18:34
[2025-02-12T19:18:34.259+0000] {subprocess.py:106} INFO - [0m19:18:34  [32mCompleted successfully[0m
[2025-02-12T19:18:34.260+0000] {subprocess.py:106} INFO - [0m19:18:34
[2025-02-12T19:18:34.260+0000] {subprocess.py:106} INFO - [0m19:18:34  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-12T19:18:35.431+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-12T19:18:35.460+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-12T19:18:35.461+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=superstore_dag, task_id=run_dbt_dim_product, run_id=scheduled__2025-02-11T00:00:00+00:00, execution_date=20250211T000000, start_date=20250212T191829, end_date=20250212T191835
[2025-02-12T19:18:35.488+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-12T19:18:35.502+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-12T19:18:35.517+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
