[2025-02-11T18:24:38.188+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T18:24:38.203+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superstore_dag.run_dbt_dim_product scheduled__2025-02-10T00:00:00+00:00 [queued]>
[2025-02-11T18:24:38.211+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superstore_dag.run_dbt_dim_product scheduled__2025-02-10T00:00:00+00:00 [queued]>
[2025-02-11T18:24:38.212+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-11T18:24:38.224+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_dbt_dim_product> on 2025-02-10 00:00:00+00:00
[2025-02-11T18:24:38.229+0000] {standard_task_runner.py:72} INFO - Started process 521 to run task
[2025-02-11T18:24:38.232+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'superstore_dag', 'run_dbt_dim_product', 'scheduled__2025-02-10T00:00:00+00:00', '--job-id', '200', '--raw', '--subdir', 'DAGS_FOLDER/superstore_dag.py', '--cfg-path', '/tmp/tmpvhmdd9e0']
[2025-02-11T18:24:38.234+0000] {standard_task_runner.py:105} INFO - Job 200: Subtask run_dbt_dim_product
[2025-02-11T18:24:38.251+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-11T18:24:38.291+0000] {task_command.py:467} INFO - Running <TaskInstance: superstore_dag.run_dbt_dim_product scheduled__2025-02-10T00:00:00+00:00 [running]> on host 9cd0ccfaeb2e
[2025-02-11T18:24:38.292+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-11T18:24:38.371+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='superstore_dag' AIRFLOW_CTX_TASK_ID='run_dbt_dim_product' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-10T00:00:00+00:00'
[2025-02-11T18:24:38.372+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-11T18:24:38.396+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-11T18:24:38.397+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /dbt/superstore/ && dbt run --select dim_product']
[2025-02-11T18:24:38.407+0000] {subprocess.py:99} INFO - Output:
[2025-02-11T18:24:41.994+0000] {subprocess.py:106} INFO - [0m18:24:41  Running with dbt=1.9.2
[2025-02-11T18:24:42.585+0000] {subprocess.py:106} INFO - [0m18:24:42  Registered adapter: postgres=1.9.0
[2025-02-11T18:24:42.802+0000] {subprocess.py:106} INFO - [0m18:24:42  Unable to do partial parsing because profile has changed
[2025-02-11T18:24:44.016+0000] {subprocess.py:106} INFO - [0m18:24:44  [[33mWARNING[0m]: Did not find matching node for patch with name 'fact_sales' in the 'models' section of file 'models/example/schema.yml'
[2025-02-11T18:24:44.389+0000] {subprocess.py:106} INFO - [0m18:24:44  [[33mWARNING[0m]: Test 'test.superstore_project.unique_fact_sales_order_hash_key.955b6af71f' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-11T18:24:44.390+0000] {subprocess.py:106} INFO - [0m18:24:44  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_order_hash_key.ef4146245b' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-11T18:24:44.391+0000] {subprocess.py:106} INFO - [0m18:24:44  [[33mWARNING[0m]: Test 'test.superstore_project.unique_fact_sales_order_id.27d0b5b8b9' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-11T18:24:44.392+0000] {subprocess.py:106} INFO - [0m18:24:44  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_order_id.f6f073d70b' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-11T18:24:44.393+0000] {subprocess.py:106} INFO - [0m18:24:44  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_customer_hash_key.1fc8c11439' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-11T18:24:44.393+0000] {subprocess.py:106} INFO - [0m18:24:44  [[33mWARNING[0m]: Test 'test.superstore_project.relationships_fact_sales_customer_hash_key__customer_hash_key__ref_dim_customer_.17da0cebd2' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-11T18:24:44.394+0000] {subprocess.py:106} INFO - [0m18:24:44  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_product_hash_key.a3a002cd4b' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-11T18:24:44.395+0000] {subprocess.py:106} INFO - [0m18:24:44  [[33mWARNING[0m]: Test 'test.superstore_project.relationships_fact_sales_product_hash_key__product_hash_key__ref_dim_product_.c5bbd01abb' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-11T18:24:44.395+0000] {subprocess.py:106} INFO - [0m18:24:44  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_location_hash_key.2ae8fd54cc' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-11T18:24:44.396+0000] {subprocess.py:106} INFO - [0m18:24:44  [[33mWARNING[0m]: Test 'test.superstore_project.relationships_fact_sales_location_hash_key__location_hash_key__ref_dim_location_.dc1a855dfb' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-11T18:24:44.397+0000] {subprocess.py:106} INFO - [0m18:24:44  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_order_date.d04f309174' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-11T18:24:44.398+0000] {subprocess.py:106} INFO - [0m18:24:44  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_ship_date.2574bac0f3' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-11T18:24:44.399+0000] {subprocess.py:106} INFO - [0m18:24:44  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_sales.2251c04d7d' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-11T18:24:44.399+0000] {subprocess.py:106} INFO - [0m18:24:44  [[33mWARNING[0m]: Test 'test.superstore_project.dbt_utils_expression_is_true_fact_sales_sales__sales_0.7f4fbe8968' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-11T18:24:44.400+0000] {subprocess.py:106} INFO - [0m18:24:44  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_quantity.123217c37f' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-11T18:24:44.400+0000] {subprocess.py:106} INFO - [0m18:24:44  [[33mWARNING[0m]: Test 'test.superstore_project.dbt_utils_expression_is_true_fact_sales_quantity__quantity_0.7112c44c4b' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-11T18:24:44.401+0000] {subprocess.py:106} INFO - [0m18:24:44  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_discount.22010f5285' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-11T18:24:44.402+0000] {subprocess.py:106} INFO - [0m18:24:44  [[33mWARNING[0m]: Test 'test.superstore_project.dbt_utils_expression_is_true_fact_sales_discount__discount_0.37582520d5' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-11T18:24:44.402+0000] {subprocess.py:106} INFO - [0m18:24:44  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_profit.c7a9f000f9' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-11T18:24:44.483+0000] {subprocess.py:106} INFO - [0m18:24:44  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-02-11T18:24:44.483+0000] {subprocess.py:106} INFO - There are 1 unused configuration paths:
[2025-02-11T18:24:44.484+0000] {subprocess.py:106} INFO - - models.superstore_project.dim_product
[2025-02-11T18:24:44.663+0000] {subprocess.py:106} INFO - [0m18:24:44  Found 5 models, 8 data tests, 1 source, 431 macros
[2025-02-11T18:24:44.665+0000] {subprocess.py:106} INFO - [0m18:24:44
[2025-02-11T18:24:44.666+0000] {subprocess.py:106} INFO - [0m18:24:44  Concurrency: 1 threads (target='prod')
[2025-02-11T18:24:44.667+0000] {subprocess.py:106} INFO - [0m18:24:44
[2025-02-11T18:24:44.801+0000] {subprocess.py:106} INFO - [0m18:24:44  1 of 1 START sql incremental model core.dim_product ............................ [RUN]
[2025-02-11T18:24:45.054+0000] {subprocess.py:106} INFO - [0m18:24:45  1 of 1 OK created sql incremental model core.dim_product ....................... [[32mINSERT 0 8474[0m in 0.25s]
[2025-02-11T18:24:45.071+0000] {subprocess.py:106} INFO - [0m18:24:45
[2025-02-11T18:24:45.071+0000] {subprocess.py:106} INFO - [0m18:24:45  Finished running 1 incremental model in 0 hours 0 minutes and 0.40 seconds (0.40s).
[2025-02-11T18:24:45.121+0000] {subprocess.py:106} INFO - [0m18:24:45
[2025-02-11T18:24:45.122+0000] {subprocess.py:106} INFO - [0m18:24:45  [32mCompleted successfully[0m
[2025-02-11T18:24:45.122+0000] {subprocess.py:106} INFO - [0m18:24:45
[2025-02-11T18:24:45.123+0000] {subprocess.py:106} INFO - [0m18:24:45  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-11T18:24:46.274+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-11T18:24:46.303+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-11T18:24:46.304+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=superstore_dag, task_id=run_dbt_dim_product, run_id=scheduled__2025-02-10T00:00:00+00:00, execution_date=20250210T000000, start_date=20250211T182438, end_date=20250211T182446
[2025-02-11T18:24:46.352+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-11T18:24:46.371+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-11T18:24:46.373+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
