[2025-02-12T19:18:38.133+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T19:18:38.148+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superstore_dag.run_dbt_dim_location scheduled__2025-02-11T00:00:00+00:00 [queued]>
[2025-02-12T19:18:38.155+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superstore_dag.run_dbt_dim_location scheduled__2025-02-11T00:00:00+00:00 [queued]>
[2025-02-12T19:18:38.156+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-12T19:18:38.168+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_dbt_dim_location> on 2025-02-11 00:00:00+00:00
[2025-02-12T19:18:38.172+0000] {standard_task_runner.py:72} INFO - Started process 119 to run task
[2025-02-12T19:18:38.174+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'superstore_dag', 'run_dbt_dim_location', 'scheduled__2025-02-11T00:00:00+00:00', '--job-id', '213', '--raw', '--subdir', 'DAGS_FOLDER/superstore_dag.py', '--cfg-path', '/tmp/tmpyxpgyt9s']
[2025-02-12T19:18:38.176+0000] {standard_task_runner.py:105} INFO - Job 213: Subtask run_dbt_dim_location
[2025-02-12T19:18:38.188+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-12T19:18:38.222+0000] {task_command.py:467} INFO - Running <TaskInstance: superstore_dag.run_dbt_dim_location scheduled__2025-02-11T00:00:00+00:00 [running]> on host 9cd0ccfaeb2e
[2025-02-12T19:18:38.223+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-12T19:18:38.296+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='superstore_dag' AIRFLOW_CTX_TASK_ID='run_dbt_dim_location' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-11T00:00:00+00:00'
[2025-02-12T19:18:38.297+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-12T19:18:38.309+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-12T19:18:38.310+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /dbt/superstore/ && dbt run --select dim_location']
[2025-02-12T19:18:38.316+0000] {subprocess.py:99} INFO - Output:
[2025-02-12T19:18:40.099+0000] {subprocess.py:106} INFO - [0m19:18:40  Running with dbt=1.9.2
[2025-02-12T19:18:40.337+0000] {subprocess.py:106} INFO - [0m19:18:40  Registered adapter: postgres=1.9.0
[2025-02-12T19:18:40.513+0000] {subprocess.py:106} INFO - [0m19:18:40  Unable to do partial parsing because a project config has changed
[2025-02-12T19:18:41.687+0000] {subprocess.py:106} INFO - [0m19:18:41  [[33mWARNING[0m]: Did not find matching node for patch with name 'fact_sales' in the 'models' section of file 'models/example/schema.yml'
[2025-02-12T19:18:42.054+0000] {subprocess.py:106} INFO - [0m19:18:42  [[33mWARNING[0m]: Test 'test.superstore_project.unique_fact_sales_order_hash_key.955b6af71f' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:42.055+0000] {subprocess.py:106} INFO - [0m19:18:42  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_order_hash_key.ef4146245b' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:42.056+0000] {subprocess.py:106} INFO - [0m19:18:42  [[33mWARNING[0m]: Test 'test.superstore_project.unique_fact_sales_order_id.27d0b5b8b9' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:42.056+0000] {subprocess.py:106} INFO - [0m19:18:42  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_order_id.f6f073d70b' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:42.057+0000] {subprocess.py:106} INFO - [0m19:18:42  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_customer_hash_key.1fc8c11439' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:42.057+0000] {subprocess.py:106} INFO - [0m19:18:42  [[33mWARNING[0m]: Test 'test.superstore_project.relationships_fact_sales_customer_hash_key__customer_hash_key__ref_dim_customer_.17da0cebd2' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:42.058+0000] {subprocess.py:106} INFO - [0m19:18:42  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_product_hash_key.a3a002cd4b' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:42.058+0000] {subprocess.py:106} INFO - [0m19:18:42  [[33mWARNING[0m]: Test 'test.superstore_project.relationships_fact_sales_product_hash_key__product_hash_key__ref_dim_product_.c5bbd01abb' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:42.059+0000] {subprocess.py:106} INFO - [0m19:18:42  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_location_hash_key.2ae8fd54cc' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:42.060+0000] {subprocess.py:106} INFO - [0m19:18:42  [[33mWARNING[0m]: Test 'test.superstore_project.relationships_fact_sales_location_hash_key__location_hash_key__ref_dim_location_.dc1a855dfb' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:42.060+0000] {subprocess.py:106} INFO - [0m19:18:42  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_order_date.d04f309174' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:42.061+0000] {subprocess.py:106} INFO - [0m19:18:42  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_ship_date.2574bac0f3' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:42.061+0000] {subprocess.py:106} INFO - [0m19:18:42  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_sales.2251c04d7d' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:42.062+0000] {subprocess.py:106} INFO - [0m19:18:42  [[33mWARNING[0m]: Test 'test.superstore_project.dbt_utils_expression_is_true_fact_sales_sales__sales_0.7f4fbe8968' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:42.062+0000] {subprocess.py:106} INFO - [0m19:18:42  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_quantity.123217c37f' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:42.063+0000] {subprocess.py:106} INFO - [0m19:18:42  [[33mWARNING[0m]: Test 'test.superstore_project.dbt_utils_expression_is_true_fact_sales_quantity__quantity_0.7112c44c4b' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:42.063+0000] {subprocess.py:106} INFO - [0m19:18:42  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_discount.22010f5285' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:42.064+0000] {subprocess.py:106} INFO - [0m19:18:42  [[33mWARNING[0m]: Test 'test.superstore_project.dbt_utils_expression_is_true_fact_sales_discount__discount_0.37582520d5' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:42.064+0000] {subprocess.py:106} INFO - [0m19:18:42  [[33mWARNING[0m]: Test 'test.superstore_project.not_null_fact_sales_profit.c7a9f000f9' (models/example/schema.yml) depends on a node named 'fact_sales' in package '' which was not found
[2025-02-12T19:18:42.309+0000] {subprocess.py:106} INFO - [0m19:18:42  Found 5 models, 10 data tests, 1 source, 431 macros
[2025-02-12T19:18:42.313+0000] {subprocess.py:106} INFO - [0m19:18:42
[2025-02-12T19:18:42.313+0000] {subprocess.py:106} INFO - [0m19:18:42  Concurrency: 1 threads (target='prod')
[2025-02-12T19:18:42.314+0000] {subprocess.py:106} INFO - [0m19:18:42
[2025-02-12T19:18:42.401+0000] {subprocess.py:106} INFO - [0m19:18:42  1 of 1 START sql incremental model core.dim_location ........................... [RUN]
[2025-02-12T19:18:42.586+0000] {subprocess.py:106} INFO - [0m19:18:42  1 of 1 OK created sql incremental model core.dim_location ...................... [[32mINSERT 0 0[0m in 0.18s]
[2025-02-12T19:18:42.597+0000] {subprocess.py:106} INFO - [0m19:18:42
[2025-02-12T19:18:42.598+0000] {subprocess.py:106} INFO - [0m19:18:42  Finished running 1 incremental model in 0 hours 0 minutes and 0.28 seconds (0.28s).
[2025-02-12T19:18:42.646+0000] {subprocess.py:106} INFO - [0m19:18:42
[2025-02-12T19:18:42.647+0000] {subprocess.py:106} INFO - [0m19:18:42  [32mCompleted successfully[0m
[2025-02-12T19:18:42.647+0000] {subprocess.py:106} INFO - [0m19:18:42
[2025-02-12T19:18:42.648+0000] {subprocess.py:106} INFO - [0m19:18:42  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-12T19:18:43.528+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-12T19:18:43.550+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-12T19:18:43.550+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=superstore_dag, task_id=run_dbt_dim_location, run_id=scheduled__2025-02-11T00:00:00+00:00, execution_date=20250211T000000, start_date=20250212T191838, end_date=20250212T191843
[2025-02-12T19:18:43.593+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-12T19:18:43.608+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-12T19:18:43.611+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
